### ISSUE TITLE
How do I install these to an OpenComputers Computer?

### ISSUE THREAD

**Issue by Taggart1993** [zenith391/zenith391-Pipboys#1]
I need to know how I'd install this using a pastebin run, or a bit of copying & pasting code.

**Comment by zenith391** [comment]
You need to install [Fuchas](https://github.com/zenith391/Fuchas) and then use the `apm install [package name]` command in the terminal.
You could theoritically put some of those on OpenOS but most programs won't work on other systems than Fuchas.
